server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost/usuarios
    username: root
    password: Admin77.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka